exp_name: "gcntf_2500_extended_release"
model_type: "gcntf"
nblocks: 1
nlayers: 10
nchannels: 16
kernel_size: 5
dilation_growth: 3
tfilm_block_size: 128
pad_input_to_receptive_field: false
causal: false

max_epochs: 150
preload: true
sample_rate: 44100
shuffle: true
train_subset: "train"
val_subset: "val"
eval_subset: "test"
train_length: 118400
train_fraction: 1.0
eval_length: 131072
batch_size: 12
num_workers: 0
precision: 16
eval_precision: 32
eval_audo_save_dir: "./audio"
